version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - HOST=0.0.0.0
      - FLASK_APP=auth/__init__.py
    env_file:
      - ./.env
  db:
    image: "postgres:alpine"